# Site settings
title: "Joshua Miguel Gloria"
name: "Joshua Miguel Laresma-Gloria"

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/jmgloria07
 - title: LinkedIn
   url: https://ph.linkedin.com/in/joshua-miguel-gloria-600006b7

#Any buzzword skills you want to include
skills:
 - Java
 - Struts2
 - Spring
 - Spring Boot
 - JSP/Servlets
 - HTML/CSS
 - JavaScript/jQuery
 - BASH Scripting
 - SQL
 - SOAP & REST
 - Microservices
 - API design
 - Jenkins
 - Gradle
 - Maven
 - Ant
 - Git
 - SVN
 - IBM ClearCase
 - Agile
 - Waterfall
 - Apache Tomcat
 - IBM WebSphere
 - IBM Red Hat OpenShift
 - CI/CD

#Work experience is required
roles:
 - title: Systems Engineer
   start: 2018
   end: Present
   employer: Tata Consultancy Services
   description: TCS is a multi-national IT services company based in India, that caters process offshoring, consultancy as well as business solutions. Working as one of their engineers, I became part of different teams that maintain and develop different portfolios of web applications, as well as start a project from ground up, all with close coordination with their respective clients.
 - title: Application Management Engineer
   start: 2015
   end: 2018
   employer: Pointwest Innovations
   description: Pointwest is a relatively young local IT company that was established during the early 2000s. Most of the projects I handled were support of existing web applications, but I also had chances to perform as a coordinator to close the offshore and client communication.
 - title: Software Engineer
   start: 2014
   end: 2015
   employer: PCM BPO LLC
   description: PCM BPO LLC is the local extension of PCM Incorporated, and handles the IT and Marketing at offshore. As a fresh graduate, I was trained under their bootcamp program and graduated as a junior developer, which then be fully integrated with the team.
 - title: Developer Trainee
   start: 2012
   end: 2012
   employer: AssistPlus Incorporated
   description: AssistPlus is a local software solutions provider with local clients that partnered with the university I was in. As a developer trainee, AssistPlus allowed me to learn by experience by being close part of the team. They gave me modules to work on to be integrated with the application they were creating.
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2013
   subject: Computer Engineering
   school: "Far Eastern University- East Asia College"

#List of interesting Github repo/projects to include - optional
github:
 - jmgloria07/jmgloria07.github.io
 - jmgloria07/gracenote
 - jmgloria07/gracenote-angular
 - jmgloria07/toktive
 - jmgloria07/toktive-web

intro: |
 Software Developer with 6 years experience specializing in Web Development. Supported and developed projects on both front and back-end, as well as exposed to Agile and Continuous Integration/Continuous Development (CI/CD). Looking for an organization that can cultivate and utilize the said skills.<br/><br/>
 I find building applications interesting. I usually wind up looking into applications I'm using and envision how it could implemented in code applying my six years of expertise in application development.<br/><br/>
 I thrive the best at environments with productive and busy atmosphere, allowing me to get into "the zone." I also practice at the utmost both community and enterprise defined coding standards, as I believe that good codes are concise, readable, and contextual.<br/><br/>
 During spare time, I enjoy books, movies, plastic models, and games at the comfort of home. While indoors are my go-to past-time, I also enjoy mountain climbing, diving, and out-of-town experiences outdoors.
